name: eggnstone_amazon_chime
copyright: 2020 Mark Eggenstein
description: A wrapper for the Amazon Chime SDKs. Allows to join Chime meetings using audio and video.
homepage: https://github.com/eggnstone/eggnstone_amazon_chime

version: 0.5.7

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.eggnstone.chime
        pluginClass: ChimePlugin
      ios:
        pluginClass: EggnstoneAmazonChimePlugin
      #web:
      #  pluginClass: ChimePlugin
      #  fileName: ChimePlugin.dart
